version: 2

project_name: aerie

builds:
  - id: aerie
    main: ./main.go
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - id: release_archive
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md

release:
  github:
    owner: enclave-ci
    name: aerie

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"
